name: Create PR on Tag Creation

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Extract tag details
      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Create a pull request
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          base: staging
          branch: development
          title: Fast Forward Release ${{ env.TAG_NAME }} to Staging Environment
          body: FILL IN HERE
          draft: false
