name: Create Staging FF Pull Request

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Extract tag details
      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Create a temporary branch at the tag
      - name: Create temporary branch
        run: |
          git fetch --tags
          git checkout ${{ env.TAG_NAME }}
          TEMP_BRANCH="temp/${{ env.TAG_NAME }}"
          git checkout -b $TEMP_BRANCH
          git push origin $TEMP_BRANCH
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV

      # Create a pull request to fast-forward staging to the tag
      - name: Create a pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base staging \
            --head ${{ env.TEMP_BRANCH }} \
            --title "Fast Forward Staging to ${TAG_NAME}" \
            --body "FILL IN HERE" \
            --repo ${{ github.repository }}
