name: Create Staging FF Pull Request

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Extract tag details
      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Create a temporary branch at the tag
      - name: Create temporary branch
        run: |
          git fetch --tags
          git checkout ${{ env.TAG_NAME }}
          TEMP_BRANCH="temp/staging/${{ env.TAG_NAME }}"
          git checkout -b $TEMP_BRANCH
          git push origin $TEMP_BRANCH
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV

      # Create a pull request to fast-forward staging to the tag
      - name: Create a pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BODY="This pull request was automatically created based on a new tag **${TAG_NAME}**. "
          PR_BODY+="This PR is to fast-forward the staging branch to **${TAG_NAME}**.<br/><br/>"
          PR_BODY+="When ready for release, please add a comment with the message: \`/ff\`. "
          PR_BODY+="This will fast forward the branch to the designated release.<br/><br/>"
          PR_BODY+="If you would like to skip this release, simply close the pull request. "
          PR_BODY+="You can delete the temporary branch as well when you close the PR.<br/><br/>"
          PR_BODY+="Thank you!"

          gh pr create \
            --base staging \
            --head ${{ env.TEMP_BRANCH }} \
            --title "Fast Forward Staging to ${TAG_NAME}" \
            --body "$PR_BODY" \
            --repo ${{ github.repository }}
