name: Validate Fast-Forward Merge

on:
  issue_comment:
    types: [created]

jobs:
  validate_ff:
    # Run only if the comment is on a pull request and starts with /ff
    if: github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/ff')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Extract Branches
        id: extract_branches
        run: |
          cat "$GITHUB_EVENT_PATH"
          BASE_BRANCH=$(jq -r .issue.pull_request.base.ref < "$GITHUB_EVENT_PATH")
          HEAD_BRANCH=$(jq -r .issue.pull_request.head.ref < "$GITHUB_EVENT_PATH")
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "HEAD_BRANCH=$HEAD_BRANCH" >> $GITHUB_ENV

      - name: Debug Branches
        run: |
          echo "Base branch: $BASE_BRANCH"
          echo "Head branch: $HEAD_BRANCH"

      - name: Check Fast-Forward Merge Possibility
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git fetch --token $GITHUB_TOKEN origin $BASE_BRANCH
          git fetch --token $GITHUB_TOKEN origin $HEAD_BRANCH
          git checkout $BASE_BRANCH
          if git merge-base --is-ancestor origin/$HEAD_BRANCH origin/$BASE_BRANCH; then
            echo "Fast-forward merge possible."
          else
            echo "Fast-forward merge is not possible." && exit 1
          fi
