name: Sync Branches (Dev->Production)

on:
  push:
    branches:
      - development

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check if a PR already exists
        id: check_pr
        run: |
          PR=$(gh pr list --base production --head ${{ github.ref }} --json number --jq '.[0].number')
          if [ -z "$PR" ]; then
            echo "PR_EXISTS=false" >> $GITHUB_ENV
          else
            echo "PR_EXISTS=true" >> $GITHUB_ENV
            echo "PR_NUMBER=$PR" >> $GITHUB_ENV
          fi

      - name: Create or Update PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$PR_EXISTS" == "false" ]]; then
            echo "Creating a new pull request from ${{ github.ref }} to production..."
            gh pr create --base production --head ${{ github.ref }} --title "Sync ${{ github.ref }} to production" --body "Automated PR to sync changes from ${{ github.ref }} to production."
          else
            echo "Pull request already exists. Updating..."
            git fetch origin production
            git checkout production
            git merge --no-edit origin/${{ github.ref }}
            git push origin production
            gh pr comment $PR_NUMBER --body "${{ github.ref }} branch was updated. Changes have been merged into this PR."
          fi
